### ISSUE TITLE
Add documentation using Google Docstrings style

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/Horizon_old#3]
Document code using following style (```constraint``` documentation in ```horizon.py```):
```
"""Apply a constraint from an interval of nodes [from_node, to_node).
    Args:
        constraint: a callable function which return the value of the constraint, min and max for a given node k
        from_node: starting node (included)
        to_node: final node (excluded)

    Returns:
        g: list of values of the constraint on the given nodes
        g_min: list of values of the lower bounds on the given nodes
        g_max: list of values of the upper bounds on the given nodes
    """
```
